#!/bin/sh

[ $# -lt 1 ] && echo "Usage: $0 PCINAME..." && exit 1

mycmd() {
    echo -e "\n\$ $* ($(date))"
    eval $*
    if [ $? -ne 0 ]; then exit 1; fi
}

dir=$(dirname $0)
for d in $*; do
    mycmd ${dir}/unvme/unvme_info $d
    mycmd ${dir}/unvme/unvme_sim_test $d
    mycmd ${dir}/unvme/unvme_api_test $d
    mycmd ${dir}/unvme/unvme_mts_test $d
    mycmd ${dir}/unvme/unvme_lat_test $d
done

if [ $# -gt 1 ]; then
    mycmd ${dir}/unvme/unvme_mcd_test $*
fi
